language: node_js
node_js:
- 6.9.5
notifications:
  email: false
  webhooks: https://ambrosio-tele.herokuapp.com/sacarinobot/travisci/133188453
  on_success: always
  on_failure: always
  on_start: always
before_script:
- npm install -g grunt-cli
deploy:
  api_key:
    secure: UPOirNX0Aek/q2gmB83E5L8NgCXG5/p1ylIdBZyLEOdZmXF2o84ltcjAZ3JH020LTPzQziVLOBebhy++tCB6GrU6pfIbD5uvXLpTLKEJSP9N5vnc0jatWOcXfNgUKp/Bv4j3JFLqrSfqtvQJFMrCxUjwdcwOTGcGWh5UAqZv1zHItG/tRDD4TjX/lvu2REvK23EQjYquAts/BmIHK3F8/DTsSZIfg7qX7zm2Vgrn1W01F7nRzbiE6jwMRqwuU78CIt4M+n5aVCDH1NJIl4b/HTuBrkklKQkfHxeNQKuFgUgkWtVPx1VkM2mWB2NtIzbeEIphiZRI3DIVO5UQIVVQXelFDftcmSh1S/Qolw4H5xw7SDQ39Bto8vrTFMXNM75hNwuIUVPLoiqJK8/dyDKlw0SPOpz0xRw9rdod3HnjAXg8WnEiPqJKiNrD09v8a0ekm83pJ1YTgCOQ1L5BeIVcFKhCjtlJ7Q28uS1Fyc1upm3v7zOJe7Pd4/L53yDGTZC5aTqIZWrHkgOCKlXlIZ1b1ubrWg/CvohaQq1oCpTsVJ+Vatu/234VDx9R2V47xRuI9VzFIm/dKr+x44h5UB6FuejNcHaMlfIvnA8LNpJhJ0vXbsrxogTsxDArXQGIVD8mr6gyEUIAnrDcpveiILkbEM2ueCnrR/iajOqcKsYdqac=
  email:
    secure: aA+1jB25hxKl9A+5m6GvcbG/oELOYyQvR+h9e+qRn2KbE8bbKgIVOYwGoyr8jRjyTTqpUNrtmCw61LTM6VwuQSa9vUUlD5VUyJNGU71lx4jRs20/l/rp0OcFgqpBWJXeFhDIgUmJEzW0HumdLd+vt5f6JQ6qfPTRGgZt2yKTS3kfWcuM57yYjXeYEypjqyHppVAjdjndylGLqPST58mx1VekD8vIv04TiiczCQ0+yBtOOoTlisMjQtAQX7I6QwX72nbL3tAKSi/CZ3q9qrwkAhE780vpJ4WyA3SSD1zeze3orXzUubkCTUf+q2XskyHMnAsZOIHEs57wxX8nzhJicPe7OdIcgSVpRh/ol5kMJia3/jR3gIZRVJFEvqwxaAOXk7VN4WUdyzLtM47n4Q6uydfe8QUIlV/Qj6fjODCctRK8JQOYufJdQxR+POCMnMlWpaEGyDIlJAGzL+L58kQ0o8BDPpYT3XEan5hNPAW52IUNXjcsWbuEeNsaueXR4g8Q5dzAJ1KiJCEL/LNIhuDhb0UHO5q94jwBD6MAPSpe2dcR0aq17/H04L2KQ5zVzVi8NzlgYl56nGZrUZasR2uGufBkRRSerg4fdT2krJCtiJVOlYGG9Y3gh+WN3ChUHVDQ8X8JzOqZ7MpG7wKjOHX0oXLF4iMhN7LTgQdbNs70zgo=
  provider: npm
